### ISSUE TITLE
GitHub Actions Runner Error: Failed to Load Docker Image Metadata During cog Push Command

### ISSUE THREAD

**Issue by tsui66** [replicate/cog#1635] opened 2024-04-29 16:14 UTC
### Issue Description
When running `cog push r8.im/aicapcut/${{ inputs.model_name }}` from a GitHub Actions runner using Docker buildx, the following error occurs:

### Error Message
```plaintext
#2 [internal] load metadata for r8.im/aicapcut/anima-pencil-v310:latest
#2 ERROR: r8.im/aicapcut/anima-pencil-v310:latest: not found
------
 > [internal] load metadata for r8.im/aicapcut/anima-pencil-v310:latest:
------
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
Dockerfile:1
--------------------
   1 | >>> FROM r8.im/aicapcut/anima-pencil-v310
--------------------
ERROR: failed to solve: r8.im/aicapcut/anima-pencil-v310: failed to resolve source metadata for r8.im/aicapcut/anima-pencil-v310

**Comment by zeke** [comment] 2024-04-29 21:02
Duplicate of https://github.com/replicate/cog/issues/1631

**Comment by zeke** [comment] 2024-06-06 14:05
This is fixed in https://github.com/replicate/cog/releases/tag/v0.9.8

**Closed by zeke** 2024-06-06 14:05 UTC
