### ISSUE TITLE
Warn user if they're trying to bundle large unused folders into Cog image

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#293] opened 2021-10-07 12:14 UTC
It is not uncommon to have a giant (several GB) conda environment folder in the Cog working dir. We should detect that and warn the user, and also point to the .dockerignore docs.

**Comment by varshneydevansh** [comment] 2023-07-05 15:43
Hi @andreasjansson and @afiaka87 I would love to take this issue as I am new to open-source and recently made few PRs and feeling confident to take new challenges.

**Comment by mattt** [comment] 2023-07-05 16:51
Files matched by `.dockerignore` aren't included in images built by Cog. #1136 adds `.dockerignore` to the `cog init` template. https://github.com/replicate/cog/issues/209 tracks documenting this functionality. I think we can close this as a dupe of #209.

Tangentially, #1095 and #1151 adds a `--separate-weights` option to `cog build`, which puts these large files into a separate layer. So files that should be ignored but aren't shouldn't impact rebuild times as much.

**Closed by mattt** 2023-07-05 16:51 UTC
Labels: enhancement, good first issue, help wanted
