### ISSUE TITLE
Getting started guide not working, ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by TasseDeCafe** [replicate/cog#1007] opened 2023-04-24 17:10 UTC
I'm following this guide: https://github.com/replicate/cog/blob/550dd219d2f6908e2557c4e448cf5a0972b87f5a/docs/getting-started.md

I'm on a Mac M1. I got the following error after following the first steps and running "cog predict -i @input.jpg"

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/site-packages/cog/__init__.py", line 1, in <module>
    from pydantic import BaseModel
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ImportError: cannot import name dataclass_transform
ⅹ Failed to get container status: exit status 1
```

**Comment by zeke** [comment] 2023-04-24 19:59
Thanks for reporting. This looks like a duplicate of https://github.com/replicate/cog/issues/958. Closing this to keep it all in once place.

**Closed by zeke** 2023-04-24 19:59 UTC
