### ISSUE TITLE
Looking for Tutorial to understand the profouness of COG

### ISSUE THREAD

**Issue by sentient-22** [replicate/cog#1087] opened 2023-06-12 11:56 UTC
The README.md fails to simulate the tutorial 

Machine : Apple M2 pro 

Output: Different sort of error keep coming out while running `cog predict -i @image.jpg`

I would request to provide a clear and tested tutorial for darwin/arm64 arch or ubuntu on perspective of `cog debug Dockerfile`

**Comment by mattt** [comment] 2023-06-12 16:11
Hi, @sentient-22. Can you please share the specific output that you're seeing and the commands that produced them?

**Comment by mattt** [comment] 2023-06-13 16:27
@sentient-22 I appreciate your taking the time to file these issues. I understand that things aren't working as expected, and want to fix that. To that end, it's helpful to have a clear set of inputs and outputs to test against. That way, I can be sure that I've actually addressed the problem you're facing.

To clarify, is this the same issue as what you reported in #1085? Or is this something else?

**Comment by sentient-22** [comment] 2023-06-13 18:03
@mattt  yes  #1085 is right context; let me know if you need any other set of variable and its value;

**Comment by sentient-22** [comment] 2023-06-17 21:12
@mattt  I think i found a hope, i would like to know the arch and emulator details regarding cog support ?

In english  plz furnish me list of arch and emulator which are supported by cog program.

-Thanks

**Comment by mattt** [comment] 2023-06-26 11:12
Closing as duplicate of https://github.com/replicate/cog/issues/1085

The platform issue was resolved by https://github.com/replicate/cog/pull/1114

Work to update the getting started guide is tracked by https://github.com/replicate/cog/issues/336.

**Closed as not planned by mattt** 2023-06-26 11:12 UTC
