### ISSUE TITLE
Support progressive output in `cog predict`

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#484] opened 2022-03-12 00:50 UTC
Currently if you do `cog predict` with a yielding predictor, it prints all the results (including file contents) to stdout.

Related to https://github.com/replicate/cog/issues/411

**Comment by bfirsh** [comment] 2022-03-12 00:58
This is effectively a duplicate of #411 -- it'll be the exact same implementation for now.

**Comment by zeke** [comment] 2022-03-14 19:45
Looks like a dupe. Closing!

**Closed by zeke** 2022-03-14 19:45 UTC
