### ISSUE TITLE
Image Builds getting stuck at "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by tonyhopkins994** [replicate/cog#1925] opened 2024-09-04 13:06 UTC
Whenever I am trying to push a model to Replicate the process gets stuck when building the image as it comes to pip install step.

```
Building Docker image from environment in cog.yaml as r8.im/tonyhopkins994/...
[+] Building 15.5s (10/12)                                                                               docker:default
 => [internal] load .dockerignore                                                                                  0.6s
 => => transferring context: 357B                                                                                  0.1s
 => [internal] load build definition from Dockerfile                                                               0.9s
 => => transferring dockerfile: 315B                                                                               0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4                                                       2.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84  0.0s
 => [internal] load metadata for r8.im/cog-base:cuda11.8-python3.9                                                 2.4s
 => [auth] cog-base:pull token for r8.im                                                                           0.0s
 => [1/5] FROM r8.im/cog-base:cuda11.8-python3.9@sha256:60b76d38c9c0869a1f634a620d37e45db364ef832c39fd2703ba23b37  0.0s
 => [internal] load build context                                                                                  0.5s
 => => transferring context: 425B                                                                                  0.1s
 => CACHED [2/5] COPY .cog/tmp/build20240904182212.7461832423469108/requirements.txt /tmp/requirements.txt         0.0s
 => ERROR [3/5] RUN pip install -r /tmp/requirements.txt                                                           5.4s
------
 > [3/5] RUN pip install -r /tmp/requirements.txt:
4.580 /root/.pyenv/pyenv.d/exec/pip-rehash/pip: line 20:    83 Illegal instruction     "$PYENV_COMMAND_PATH" "$@"
------
Dockerfile:4
--------------------
   2 |     FROM r8.im/cog-base:cuda11.8-python3.9
   3 |     COPY .cog/tmp/build20240904182212.7461832423469108/requirements.txt /tmp/requirements.txt
   4 | >>> RUN pip install -r /tmp/requirements.txt
   5 |     WORKDIR /src
   6 |     EXPOSE 5000
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r /tmp/requirements.txt" did not complete successfully: exit code: 132
ⅹ Failed to build Docker image: exit status 1
```

cog.yaml contents: 

```
# Configuration for Cog ⚙️
# Reference: https://github.com/replicate/cog/blob/main/docs/yaml.md

build:
  gpu: true
  cuda: "11.8"
  python_version: "3.9"

  python_packages:
    - torch
    - torchvision
    - torchaudio
    - torchsde
    - transformers>=4.28.1
    - safetensors>=0.3.0
    - accelerate
    - Pillow
    - scipy
    - tqdm
    - diffusers>=0.30.0


predict: "predict.py:Predictor"

```

I've tried pushing 3 different models that have successfully been built and run before and they're all getting stuck with this error now.
I've been pushing models to Replicate using cog for a while but havent come across this issue before. Any help is appreciated : )

**Comment by woodybury** [comment] 2024-09-04 19:41
@tonyhopkins994 I'm having same exact issue - model was successfully built just yesterday :/ any luck?

**Comment by Sagnik2810Sarkar** [comment] 2024-09-05 05:28
> @tonyhopkins994 I'm having same exact issue - model was successfully built just yesterday :/ any luck?

None so far. I've tried restarting Docker, deleting the previous version of the Docker image and doing a fresh build, restarting the VM and the PC. I can't imagine there's any problems with the actual .yaml file because I have hosted models with that config before and the problem is not even model specific.

**Comment by juyaki** [comment] 2024-09-05 13:39
Same issue for me on my Macbook since few days.
I tried to build/push using the github actions setup-cog and it worked fine so I think there is something wrong with my machine. However cog should be able to build models on any machine so this is weird.

**Comment by woodybury** [comment] 2024-09-05 14:27
thanks @juyaki can also confirm it works w/ GH actions for me. Must be an apple silicon specific issue. Maybe related to the pyenv 2.4.11?

**Comment by juyaki** [comment] 2024-09-05 16:53
I was using pyenv 2.4.10 and still got this issue, and since 2.4.10 is around since a month I think other people would have noticed...

**Comment by Sagnik2810Sarkar** [comment] 2024-09-06 10:00
Shouldn't be an apple silicon specific issue because I've been dealing with this on an intel machine.

**Comment by 8W9aG** [comment] 2024-09-06 14:24
Can you try this with `--use-cog-base-image=false` and let me know if the issue still persists?

**Comment by hervenivon** [comment] 2024-09-06 19:20
> --use-cog-base-image=false

Didn't solve the issue for me but triggered a new one: 

```
=> CANCELED [stage-1  2/11] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked set -eux; apt-get update -qq && apt-get install -qqy --no-install-recommends curl; rm -rf /var/lib/apt/lists/*; TINI_VERSION=v0.19.0; TINI_ARCH="$(dpkg --print-architectur  0.0s
------
 > [deps 3/5] RUN --mount=type=cache,target=/root/.cache/pip pip install -t /dep /tmp/cog.whl:
3.261 ERROR: cog.whl is not a valid wheel filename.
------
Dockerfile:4
--------------------
   2 |     FROM python:3.12 as deps
   3 |     COPY .cog/tmp/build20240906211900.889378794329390/cog.whl /tmp/cog.whl
   4 | >>> RUN --mount=type=cache,target=/root/.cache/pip pip install -t /dep /tmp/cog.whl
   5 |     COPY .cog/tmp/build20240906211900.889378794329390/requirements.txt /tmp/requirements.txt
   6 |     RUN --mount=type=cache,target=/root/.cache/pip pip install -t /dep -r /tmp/requirements.txt
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -t /dep /tmp/cog.whl" did not complete successfully: exit code: 1
```

**Comment by tonyhopkins994** [comment] 2024-09-06 19:22
> Can you try this with `--use-cog-base-image=false` and let me know if the issue still persists?

Tried a build with the `--use-cog-base-image=false` and got the following error:

```
Building Docker image from environment in cog.yaml as r8.im/tonyhopkins994/stable-materials...
[+] Building 160.4s (11/19)                                                                              docker:default
 => [internal] load build definition from Dockerfile                                                               0.8s
 => => transferring dockerfile: 2.21kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.5s
 => => transferring context: 357B                                                                                  0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4                                                       1.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84  0.0s
 => [internal] load metadata for docker.io/library/python:3.9                                                      5.1s
 => [internal] load metadata for docker.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04                             3.4s
 => ERROR [deps 1/5] FROM docker.io/library/python:3.9@sha256:5be6ab129779da4729eb8be146bdddc3662b7c7b6cc7a07e9  145.7s
 => => resolve docker.io/library/python:3.9@sha256:5be6ab129779da4729eb8be146bdddc3662b7c7b6cc7a07e9f5a675cdb4746  2.2s
 => => sha256:5be6ab129779da4729eb8be146bdddc3662b7c7b6cc7a07e9f5a675cdb4746c7 10.35kB / 10.35kB                   0.0s
 => => sha256:cea2608c91d4b92d9e12848f922085195ccd41242e0aa682d8a10b196afc5478 2.52kB / 2.52kB                     0.0s
 => => sha256:f995cc3ec8cf00c0e4dca3bfc4877ac1e938edc035d725f673be91018c09652a 7.27kB / 7.27kB                     0.0s
 => => sha256:8cd46d290033f265db57fd808ac81c444ec5a5b3f189c3d6d85043b647336913 49.56MB / 49.56MB                  27.8s
 => => sha256:2e6afa3f266c11e8960349e7866203a9df478a50362bb5488c45fe39d99b2707 24.05MB / 24.05MB                  11.7s
 => => sha256:2e66a70da0bec13fb3d492fcdef60fd8a5ef0a1a65c4e8a4909e26742852f0f2 64.15MB / 64.15MB                  15.3s
 => => sha256:1c8ff076d818ad6b8557e03e10c83657cc716ab287c8380054ff91571c8cae81 52.55MB / 211.27MB                148.3s
 => => sha256:b4383cf9d518a310e9475543865f99a0f42680d1b208992c065066d743b383a9 6.16MB / 6.16MB                    17.9s
 => => sha256:3fdc16599dab968128f232f839d96fc4ed7580fe9ac15c0fc041c77051dfaf6c 15.82MB / 15.82MB                  23.6s
 => => sha256:cc4dba91fd49abc8a140f5a4cbb088448d398c793c9db6bb84b1d275960f9d29 232B / 232B                        24.5s
 => => sha256:9b34a017daeaefa45a9454b0fe70629a37c243fae4ab2d652e0a75f0668a7481 2.70MB / 2.70MB                    25.9s
 => => extracting sha256:8cd46d290033f265db57fd808ac81c444ec5a5b3f189c3d6d85043b647336913                          4.7s
 => => extracting sha256:2e6afa3f266c11e8960349e7866203a9df478a50362bb5488c45fe39d99b2707                          1.4s
 => => extracting sha256:2e66a70da0bec13fb3d492fcdef60fd8a5ef0a1a65c4e8a4909e26742852f0f2                          5.4s
 => [internal] load build context                                                                                  0.7s
 => => transferring context: 58.20kB                                                                               0.0s
 => CACHED [stage-1 1/7] FROM docker.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04@sha256:8f9dd0d09d3ad3900357a1  0.0s
 => [stage-1 2/7] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked set -eux; apt-get update -qq && a  105.2s
 => CANCELED [stage-1 3/7] RUN --mount=type=cache,target=/var/cache/apt,sharing=locked apt-get update -qq && apt  44.8s
------
 > [deps 1/5] FROM docker.io/library/python:3.9@sha256:5be6ab129779da4729eb8be146bdddc3662b7c7b6cc7a07e9f5a675cdb4746c7:
------
Dockerfile:2
--------------------
   1 |     #syntax=docker/dockerfile:1.4
   2 | >>> FROM python:3.9 as deps
   3 |     COPY .cog/tmp/build20240907003028.1324282726843351/cog-0.9.20-py3-none-any.whl /tmp/cog-0.9.20-py3-none-any.whl
   4 |     RUN --mount=type=cache,target=/root/.cache/pip pip install -t /dep /tmp/cog-0.9.20-py3-none-any.whl
--------------------
ERROR: failed to solve: failed to copy: local error: tls: bad record MAC
ⅹ Failed to build Docker image: exit status 1
```

So the previous error is gone but I'm not making any sense of the newer one either : )

**Comment by 8W9aG** [comment] 2024-09-06 19:35
I think the root of the issue here is something has gone with the arm64 versions of our base images, looking into it, hoping to have a solution in a few days (takes a while to rebuild all these)

**Comment by krthr** [comment] 2024-09-08 15:36
Had the same issue in Macbook Air M1. Tried with GitHub Actions and the image was successfully built.

**Comment by NickNaskida** [comment] 2024-09-09 06:34
Same issue here

**Comment by tuxfamily** [comment] 2024-09-10 08:28
First time I (tried to) use cog and same issue on a Mac Studio (M1 Max).

Fresh install of cog (with `brew install cog`)

```
cog --version
cog version 0.9.20 (built 2024-08-19T14:53:01Z)
```

I simply tried to build [cog-face-to-sticker](https://github.com/fofr/cog-face-to-sticker) and voila.

```
------
 > [stage-0 4/7] RUN pip install -r /tmp/requirements.txt:
1.289 /root/.pyenv/pyenv.d/exec/pip-rehash/pip: line 20:    83 Illegal instruction     "$PYENV_COMMAND_PATH" "$@"
------
```

Not going further, as I'm not enough familiar with all of this; I will wait for a fix 😅

Thanks.

**Comment by 8W9aG** [comment] 2024-09-10 16:08
OK I do believe this has been fixed, running @tonyhopkins994 `cog.yaml` on my mac seems to correctly pip install, in addition to this the integration tests all now run on my mac and don't produce illegal instruction errors. I'll close this but feel free to comment if this `Illegal Instruction` issue is still haunting you. If its a different issue lets make a separate issue for that.

If you are interested as to why this happened its due to me attempting to make the python interpreter that pyenv installs optimized to increase the speed and boot times of the containers, however it included `-march=native` and `-mtune=native` which introduced instructions tuned to the builders CPU that other CPUs and emulators can't handle, see here for more info:
https://brad.net.nz/blog/2019/07/12/docker-cflags-marchnative-and-illegal-hardware-instruction/
https://stackoverflow.com/questions/54039176/mtune-and-march-when-compiling-in-a-docker-image

In the future we will be more careful here by gating the base images behind flags.

**Closed by 8W9aG** 2024-09-10 16:08 UTC

**Comment by tuxfamily** [comment] 2024-09-10 16:26
Confirmed fixed 👍🏻 

![ScreenShot-004087](https://github.com/user-attachments/assets/1bc66ada-e2a6-4f71-b85d-8f49ad732d36)

Many thanks.

And thank you for the explanation, it's interesting.
